#!/usr/bin/env python3

from pathlib import Path

InputType = list[list[int]]
ResultType = int


def load(input_path: Path) -> InputType:
    with open(input_path) as f:
        return [[int(x) for x in line.strip()] for line in f.readlines()]


def find_max_joltage(bank: list[int], battery_count: int) -> int:
    """Find the maximum possible joltage generated by bank, enabling battery_count batteries.

    As the leftmost digit has the most significant impact on the result, prioritise getting a
    large digit on the left. But don't choose as the next left-most digit a number that would
    leave us with fewer than the required number of batteries to its right.
    Having chosen a next left-most battery, recurse to find the remaining batteries."""
    assert battery_count <= len(bank)
    assert battery_count > 0

    if battery_count > 1:
        for i in range(9, -1, -1):
            if i in bank[:-(battery_count - 1)]:
                return i * 10 ** (battery_count - 1) + find_max_joltage(bank[bank.index(i) + 1:], battery_count - 1)
    else:
        for i in range(9, -1, -1):
            if i in bank:
                return i

    assert False


def part1(input_data: InputType) -> ResultType:
    return sum([
        find_max_joltage(bank, 2)
        for bank in input_data
    ])


def part2(input_data: InputType) -> ResultType:
    return sum([
        find_max_joltage(bank, 12)
        for bank in input_data
    ])
